# Generated by Django 5.2.9 on 2025-12-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
                ('medium_link', models.URLField(blank=True)),
                ('github_link', models.URLField()),
                ('youtube_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework'), ('tool', 'Tool'), ('soft', 'Soft Skill'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('completed_date', models.DateField(auto_now_add=True)),
                ('article_link', models.URLField()),
                ('github_link', models.URLField()),
                ('skills', models.ManyToManyField(related_name='projects', to='main.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('institute', models.CharField(max_length=50)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True)),
                ('skills', models.ManyToManyField(related_name='certificates', to='main.skill')),
            ],
        ),
    ]
