# Generated by Django 5.2.9 on 2025-12-22 12:48

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesettings_github_link_sitesettings_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=martor.models.MartorField(),
        ),
    ]
