# Generated by Django 5.2.9 on 2025-12-22 12:49

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_certificate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=martor.models.MartorField(),
        ),
    ]
