# Generated by Django 5.2.7 on 2025-12-23 17:16

import autoslug.fields
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_article_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('date__month',))),
                ('body', martor.models.MartorField()),
                ('medium_link', models.URLField(blank=True)),
                ('github_link', models.URLField()),
                ('youtube_link', models.URLField(blank=True)),
            ],
        ),
    ]
