# Generated by Django 5.2.7 on 2025-12-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='claps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
