# Generated by Django 5.2.9 on 2025-12-24 16:57

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_article_claps_article_view_count_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('personal', 'Personal / Hobby'), ('research', 'Research'), ('open_source', 'Open Source'), ('experimental', 'Experimental'), ('freelance', 'Freelance / Client'), ('learning', 'Learning / Practice')], default='personal', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
