# Generated by Django 5.2.9 on 2025-12-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_article_meta_description_article_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, help_text='short summary for Google search results', max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Leave empty to use article title', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Project cover image', null=True, upload_to='project_thumbnails/'),
        ),
    ]
