# Generated by Django 5.2.9 on 2025-12-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_project_meta_description_project_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='article_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
