# Generated by Django 5.2.9 on 2025-12-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_project_article_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_slug',
            field=models.CharField(blank=True, help_text="Simple Icon's icon slug", max_length=50),
        ),
    ]
